#!/bin/bash
# cleanup.sh — Remove temporary files created during documentation indexing.
#
# Usage: bash cleanup.sh <library-name>
#
# Removes all /tmp files generated by recon.py, crawl.py, extract.py,
# and verify.py for the given library. Run after confirming the generated
# skill works correctly.

set -e

if [ -z "$1" ]; then
    echo "Usage: bash cleanup.sh <library-name>"
    echo "Example: bash cleanup.sh react"
    exit 1
fi

LIB="$1"

removed=0

for target in \
    "/tmp/${LIB}-recon.json" \
    "/tmp/${LIB}-sitemap.json" \
    "/tmp/${LIB}-sitemap.json.checkpoint.json"
do
    if [ -f "$target" ]; then
        rm -f "$target"
        echo "Removed $target"
        removed=$((removed + 1))
    fi
done

for target in \
    "/tmp/${LIB}-html" \
    "/tmp/${LIB}-extracted" \
    "/tmp/${LIB}-screenshots"
do
    if [ -d "$target" ]; then
        rm -rf "$target"
        echo "Removed $target/"
        removed=$((removed + 1))
    fi
done

# Remove llms-urls files (domain-based naming, so glob for all)
for f in /tmp/*-llms-urls.txt; do
    if [ -f "$f" ]; then
        rm -f "$f"
        echo "Removed $f"
        removed=$((removed + 1))
    fi
done

if [ "$removed" -eq 0 ]; then
    echo "No temporary files found for '${LIB}'."
else
    echo "Cleaned up $removed items."
fi
